#!/usr/bin/env node

const semver = require('semver');
const { version } = require('../package.json');

const prerelease = semver.prerelease(version);
const minor = semver.minor(version);

let result = `0.${minor}`;

if (prerelease) {
    result = `${result}-${prerelease[0]}`;
}

console.log(result);
